name: Publish to Internal

on:
  workflow_dispatch:
    inputs:
      branchName:
        description: 'Branch Name (default "master")'
        required: false
        default: 'master'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{github.event.inputs.branchName}}

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

#      - name: Cache Gradle Caches
#        uses: actions/cache@v1
#        with:
#          path: ~/.gradle/caches/
#          key: cache-gradle-cache
#
#      - name: Cache Gradle Wrapper
#        uses: actions/cache@v1
#        with:
#          path: ~/.gradle/wrapper/
#          key: cache-gradle-wrapper

      - name: Build
        run: ./gradlew build
        
      - name: Assemble Release Bundle
        run: |
          ./gradlew bundleRelease
          
      - name: Sign Release
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
          
#      - name: Tag Release
#        run: |
#          version_name=${GITHUB_REF##*/}
#          echo "Tagging release with tag $version_name"
#          git tag $version_name release/$version_name
#          git push origin --tags


#      - name: set version
#        id: vars
#        run : |
#          echo "::set-output name=version_name::${GITHUB_REF##*/}"
#
#      - name: Read package.json
#        id: package
#        uses: juliangruber/read-file-action@v1
#        with:
#          path: ./app/version.properties
#
#      - name: Echo package.json
#        run: |
#          echo ${{ steps.package.outputs.content }}
#          echo ${{ steps.vars.outputs.version_name }}

      - name: Changelog
        uses: scottbrenner/generate-changelog-action@master
        id: Changelog
        env:
          REPO: ${{ github.repository }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          commitish: ${{ github.sha }}
          body: |
            Changes in this Release
            ${{ steps.Changelog.outputs.changelog }}
          draft: false
          prerelease: false
          
      - name: Create service_account.json
        run: echo '${{ secrets.SERVICE_ACCOUNT_JSON }}' > service_account.json

      - name: Deploy to Alpha
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: service_account.json
          packageName: com.viswa.dfm
          releaseFile: app/build/outputs/bundle/release/ddfm-release.aab
          track: internal
          whatsNewDirectory: distribution/
