name: CI

on:
  push:
    branches:
      - 'master'
        
  pull_request:
    branches:
      - 'master'
      - 'develop'
      - '!release/**'

jobs:
  lint:
    name: Running lints
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Restore Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Create keystore.properties file
        id: createKeystoreProperties
        run: echo '${{ secrets.KEY_STORE_PROPERTIES }}' > keystore.properties

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Running Ktlint
        run: bash ./gradlew ktlint --stacktrace

      - name: Running detekt
        run: bash ./gradlew detekt --stacktrace
  

  build:
    needs: lint
    name: Build app
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Restore Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Create keystore.properties file
        id: createKeystoreProperties
        run: echo '${{ secrets.KEY_STORE_PROPERTIES }}' > keystore.properties

      - name: Build the app
        run: ./gradlew build

