name: test file read

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: set version
        id: vars
        run: |
          echo "::set-output name=version_name::${GITHUB_REF##*/}"

      - name: Read package.json
        id: package
        uses: juliangruber/read-file-action@v1
        with:
          path: ./app/version.properties

#      - name: Echo package.json
#        run: |
#          echo ${{ steps.package.outputs.content }}
#          echo ${{ steps.vars.outputs.version_name }}

      - name: Read value from Properties-file
        id: read_property
        uses: christian-draeger/read-properties@1.0.1
        with:
          path: './app/version.properties'
          property: 'VERSION_TAG'

      - name: Do something with your bumped release version
        run: echo "${{ steps.vars.outputs.version_name }}-${{ steps.read_property.outputs.value }}"
